### ISSUE TITLE
High DPI Support

### ISSUE THREAD

**Issue by whispy** [eijah/demonsaw#3]
User interface is tiny on high DPI devices. I tried manually editing multiple `font-size` values in the `demonsaw.css.txt` file, but none of them changed the interface when I relaunched Demonsaw.

Please let me know if you need more info.

**Comment by whispy** [comment]
I didn't full read the `readme.txt`. My apologies.

**Comment by eijah** [comment]
No worries.� :-)
Out of curiosity (in case other people have
the same issue), how did you solve the problem?� Did you just edit
the CSS file?� If so, can you send me your version to I can include
it in a future release?�
Thanks!
�
-Eijah
�
I didn't full read
the `readme.txt`. My apologies.



---

**Comment by eijah** [comment]
You probably just forgot to rename the demonsaw.CSS.txt file. No worries. In the next release I'm planning on supporting actual themes via gui configuration so we won't have to deal with the renaming of the file. :)
On Aug 11, 2015 11:27 AM, Dan Berkowitz <notifications@github.com> wrote:I didn't full read the readme.txt. My apologies.

**Comment by whispy** [comment]
Yeah, I just forgot to rename it :laughing:

**Comment by eijah** [comment]
:-P All good -
thanks!
�
-Eijah
�
Yeah, I just forgot
to rename it :laughing:



---
